-- [[ GENERATED BY GEMINI COLLABORATOR - GLASSMORPHISM UI LIBRARY ]] --
local TweenService = game:GetService("TweenService")
local UserInputService = game:GetService("UserInputService")
local ReplicatedStorage = game:GetService("ReplicatedStorage")
local Players = game:GetService("Players")
local LocalPlayer = Players.LocalPlayer

-- Initialize ScreenGui
local GlassUI = Instance.new("ScreenGui")
GlassUI.Name = "GlassmorphismUI"
GlassUI.ResetOnSpawn = false
GlassUI.ZIndexBehavior = Enum.ZIndexBehavior.Sibling
if syn and syn.protect_gui then syn.protect_gui(GlassUI) end
GlassUI.Parent = LocalPlayer:WaitForChild("PlayerGui")

-- Apply Glass Style function
local function ApplyGlassStyle(instance, transparency, borderColor)
    instance.BackgroundColor3 = Color3.fromRGB(20, 30, 50)
    instance.BackgroundTransparency = transparency or 0.35
    
    local uiCorner = Instance.new("UICorner")
    uiCorner.CornerRadius = UDim.new(0, 12)
    uiCorner.Parent = instance
    
    local uiStroke = Instance.new("UIStroke")
    uiStroke.Thickness = 1.5
    uiStroke.Color = borderColor or Color3.fromRGB(0, 120, 255)
    uiStroke.Transparency = 0.4
    uiStroke.Parent = instance
end

-- Make UI Draggable function
local function MakeDraggable(gui)
    local dragging, dragInput, dragStart, startPos
    gui.InputBegan:Connect(function(input)
        if input.UserInputType == Enum.UserInputType.MouseButton1 or input.UserInputType == Enum.UserInputType.Touch then
            dragging = true
            dragStart = input.Position
            startPos = gui.Position
            input.Changed:Connect(function()
                if input.UserInputState == Enum.UserInputState.End then dragging = false end
            end)
        end
    end)
    gui.InputChanged:Connect(function(input)
        if input.UserInputType == Enum.UserInputType.MouseMovement or input.UserInputType == Enum.UserInputType.Touch then
            dragInput = input
        end
    end)
    UserInputService.InputChanged:Connect(function(input)
        if input == dragInput and dragging then
            local delta = input.Position - dragStart
            gui.Position = UDim2.new(startPos.X.Scale, startPos.X.Offset + delta.X, startPos.Y.Scale, startPos.Y.Offset + delta.Y)
        end
    end)
end

-------------------------------------------------------------------------------
-- GAME CHECKING SYSTEM (5 SECONDS)
-------------------------------------------------------------------------------
local VALID_IDS = {
    [98629859043211] = "Lobby",
    [99078474560152] = "Gameplay",
    [6516141723] = "Lobbydoor",
    [6839171747] = "Gameplaydoor",
    [88323040672117] = "DivazGame",
    [97598239454123] = "Growagarden2",
    [7577961216] = "lobbysquidgamex",
    [7577981568] = "squidgamex",
}
local currentId = game.PlaceId

-- Initialize Checking UI
local CheckUI = Instance.new("ScreenGui")
CheckUI.Name = "GameCheckUI"
CheckUI.ResetOnSpawn = false
CheckUI.Parent = LocalPlayer:WaitForChild("PlayerGui")

local CheckFrame = Instance.new("Frame")
CheckFrame.Size = UDim2.new(0, 320, 0, 140)
CheckFrame.Position = UDim2.new(0.5, -160, 0.5, -70)
ApplyGlassStyle(CheckFrame, 0.2, Color3.fromRGB(255, 215, 0))
CheckFrame.Parent = CheckUI

local CheckLogo = Instance.new("ImageLabel")
CheckLogo.Size = UDim2.new(0, 45, 0, 45)
CheckLogo.Position = UDim2.new(0.5, -22, 0, 15)
CheckLogo.Image = "rbxassetid://110980417958407"
CheckLogo.BackgroundTransparency = 1
CheckLogo.Parent = CheckFrame

local CheckText = Instance.new("TextLabel")
CheckText.Size = UDim2.new(1, 0, 0, 30)
CheckText.Position = UDim2.new(0, 0, 0, 70)
CheckText.BackgroundTransparency = 1
CheckText.Text = "Checking game..."
CheckText.TextColor3 = Color3.fromRGB(255, 255, 255)
CheckText.TextSize = 15
CheckText.Font = Enum.Font.GothamMedium
CheckText.Parent = CheckFrame

task.wait(5)
CheckUI:Destroy()

if not VALID_IDS[currentId] then
    LocalPlayer:Kick("[ENGLISH]: The script does not yet support this game.")
    return 
end

-------------------------------------------------------------------------------
-- 1. KEY SYSTEM
-------------------------------------------------------------------------------
local KeyFrame = Instance.new("Frame")
KeyFrame.Size = UDim2.new(0, 350, 0, 200)
KeyFrame.Position = UDim2.new(0.5, -175, 0.5, -100)
ApplyGlassStyle(KeyFrame, 0.25)
KeyFrame.Parent = GlassUI
MakeDraggable(KeyFrame)

local KeyTitle = Instance.new("TextLabel")
KeyTitle.Size = UDim2.new(1, 0, 0, 40)
KeyTitle.BackgroundTransparency = 1
KeyTitle.Text = "KEY SYSTEM"
KeyTitle.TextColor3 = Color3.fromRGB(255, 215, 0)
KeyTitle.TextSize = 18
KeyTitle.Font = Enum.Font.GothamBold
KeyTitle.Parent = KeyFrame

local KeyInput = Instance.new("TextBox")
KeyInput.Size = UDim2.new(0, 280, 0, 40)
KeyInput.Position = UDim2.new(0.5, -140, 0.4, 0)
KeyInput.PlaceholderText = "Enter Key Here..."
KeyInput.Text = ""
KeyInput.TextColor3 = Color3.fromRGB(255, 255, 255)
KeyInput.TextSize = 14
KeyInput.Font = Enum.Font.Gotham
ApplyGlassStyle(KeyInput, 0.6, Color3.fromRGB(255, 255, 255))
KeyInput.Parent = KeyFrame

local KeyBtn = Instance.new("TextButton")
KeyBtn.Size = UDim2.new(0, 120, 0, 35)
KeyBtn.Position = UDim2.new(0.5, -60, 0.7, 10)
KeyBtn.Text = "Verify Key"
KeyBtn.TextColor3 = Color3.fromRGB(255, 255, 255)
KeyBtn.TextSize = 14
KeyBtn.Font = Enum.Font.GothamBold
ApplyGlassStyle(KeyBtn, 0.3, Color3.fromRGB(0, 120, 255))
KeyBtn.Parent = KeyFrame

--------------------------------------------------------------------------------
-- 2. MAIN MENU INTERFACE
-------------------------------------------------------------------------------
local MainFrame = Instance.new("Frame")
MainFrame.Size = UDim2.new(0, 560, 0, 400)
MainFrame.Position = UDim2.new(0.5, -280, 0.5, -200)
MainFrame.Visible = false
ApplyGlassStyle(MainFrame, 0.3)
MainFrame.Parent = GlassUI
MakeDraggable(MainFrame)

local Header = Instance.new("Frame")
Header.Name = "Header"
Header.Size = UDim2.new(1, 0, 0, 60)
Header.Position = UDim2.new(0, 0, 0, 0)
Header.BackgroundTransparency = 1
Header.Parent = MainFrame

local HubLogo = Instance.new("ImageLabel")
HubLogo.Size = UDim2.new(0, 40, 0, 40)
HubLogo.Position = UDim2.new(0, 15, 0, 10)
HubLogo.Image = "rbxassetid://114983785805099" 
HubLogo.BackgroundTransparency = 1
HubLogo.Parent = Header

local HubName = Instance.new("TextLabel")
HubName.Size = UDim2.new(0, 300, 1, 0)
HubName.Position = UDim2.new(0, 65, 0, 0)
HubName.BackgroundTransparency = 1
HubName.Text = "TROLL HUB [Premium]"
HubName.TextColor3 = Color3.fromRGB(255, 215, 0)
HubName.TextSize = 22
HubName.Font = Enum.Font.GothamBold
HubName.TextXAlignment = Enum.TextXAlignment.Left
HubName.Parent = Header

local Body = Instance.new("Frame")
Body.Name = "Body"
Body.Size = UDim2.new(1, 0, 1, -60)
Body.Position = UDim2.new(0, 0, 0, 60)
Body.BackgroundTransparency = 1
Body.Parent = MainFrame

local Sidebar = Instance.new("ScrollingFrame")
Sidebar.Size = UDim2.new(0, 150, 1, -10)
Sidebar.Position = UDim2.new(0, 10, 0, 5)
Sidebar.BackgroundTransparency = 1
Sidebar.CanvasSize = UDim2.new(0, 0, 0, 0)
Sidebar.ScrollBarThickness = 2
Sidebar.Parent = Body

local SidebarLayout = Instance.new("UIListLayout")
SidebarLayout.Padding = UDim.new(0, 8)
SidebarLayout.Parent = Sidebar

local Container = Instance.new("Frame")
Container.Size = UDim2.new(1, -180, 1, -10)
Container.Position = UDim2.new(0, 170, 0, 5)
Container.BackgroundTransparency = 1
Container.Parent = Body

local ToggleUIBtn = Instance.new("ImageButton")
ToggleUIBtn.Size = UDim2.new(0, 45, 0, 45)
ToggleUIBtn.Position = UDim2.new(0, 15, 0, 15)
ToggleUIBtn.Image = "rbxassetid://97910139651355" 
ToggleUIBtn.Visible = false
ApplyGlassStyle(ToggleUIBtn, 0.2, Color3.fromRGB(255, 215, 0))
ToggleUIBtn.Parent = GlassUI

ToggleUIBtn.MouseButton1Click:Connect(function()
    MainFrame.Visible = not MainFrame.Visible
end)

-------------------------------------------------------------------------------
-- 3. LOADING BAR SYSTEM
-------------------------------------------------------------------------------
local LoadingFrame = Instance.new("Frame")
LoadingFrame.Size = UDim2.new(0, 400, 0, 100)
LoadingFrame.Position = UDim2.new(0.5, -200, 0.5, -50)
LoadingFrame.Visible = false
ApplyGlassStyle(LoadingFrame, 0.25)
LoadingFrame.Parent = GlassUI

local LoadText = Instance.new("TextLabel")
LoadText.Size = UDim2.new(1, 0, 0, 30)
LoadText.BackgroundTransparency = 1
LoadText.Text = "Loading Assets: 0%"
LoadText.TextColor3 = Color3.fromRGB(255, 255, 255)
LoadText.TextSize = 14
LoadText.Font = Enum.Font.GothamMedium
LoadText.Parent = LoadingFrame

local BarBg = Instance.new("Frame")
BarBg.Size = UDim2.new(0, 360, 0, 15)
BarBg.Position = UDim2.new(0.5, -180, 0.6, 5)
ApplyGlassStyle(BarBg, 0.6, Color3.fromRGB(255,255,255))
BarBg.Parent = LoadingFrame

local BarFill = Instance.new("Frame")
BarFill.Size = UDim2.new(0, 0, 1, 0)
BarFill.BackgroundColor3 = Color3.fromRGB(0, 120, 255)
local fillCorner = Instance.new("UICorner")
fillCorner.CornerRadius = UDim.new(0, 12)
fillCorner.Parent = BarFill
BarFill.Parent = BarBg

local function StartLoading()
    KeyFrame.Visible = false
    LoadingFrame.Visible = true
    for i = 1, 100 do
        task.wait(0.02)
        LoadText.Text = "Loading Assets: " .. i .. "%"
        BarFill.Size = UDim2.new(i/100, 0, 1, 0)
    end
    task.wait(0.2)
    LoadingFrame.Visible = false
    MainFrame.Visible = true
    ToggleUIBtn.Visible = true
end

KeyBtn.MouseButton1Click:Connect(function()
    local keyChuan = "bloxypremium2026"
    if KeyInput.Text == keyChuan then
        StartLoading()
    else
        KeyInput.Text = ""
        KeyInput.PlaceholderText = "Invalid Key! Try again."
    end
end)

-------------------------------------------------------------------------------
-- 4. INTERFACE CREATION HANDLERS
-------------------------------------------------------------------------------
local FirstTab = true

function CreateTab(tabName)
    local TabPage = Instance.new("ScrollingFrame")
    TabPage.Size = UDim2.new(1, 0, 1, 0)
    TabPage.BackgroundTransparency = 1
    TabPage.Visible = false
    TabPage.CanvasSize = UDim2.new(0, 0, 0, 0)
    TabPage.ScrollBarThickness = 4
    TabPage.Parent = Container
    
    local TabPageLayout = Instance.new("UIListLayout")
    TabPageLayout.Padding = UDim.new(0, 10)
    TabPageLayout.Parent = TabPage
    
    TabPageLayout:GetPropertyChangedSignal("AbsoluteContentSize"):Connect(function()
        TabPage.CanvasSize = UDim2.new(0, 0, 0, TabPageLayout.AbsoluteContentSize.Y + 30)
    end)
    
    local TabBtn = Instance.new("TextButton")
    TabBtn.Size = UDim2.new(1, -5, 0, 35)
    TabBtn.Text = tabName
    TabBtn.TextColor3 = Color3.fromRGB(255, 255, 255)
    TabBtn.TextSize = 13
    TabBtn.Font = Enum.Font.GothamMedium
    ApplyGlassStyle(TabBtn, 0.5, Color3.fromRGB(0, 120, 255))
    TabBtn.Parent = Sidebar
    
    TabBtn.MouseButton1Click:Connect(function()
        for _, page in pairs(Container:GetChildren()) do
            if page:IsA("ScrollingFrame") then page.Visible = false end
        end
        for _, btn in pairs(Sidebar:GetChildren()) do
            if btn:IsA("TextButton") then 
                TweenService:Create(btn, TweenInfo.new(0.2), {BackgroundTransparency = 0.5}):Play()
            end
        end
        TabPage.Visible = true
        TweenService:Create(TabBtn, TweenInfo.new(0.2), {BackgroundTransparency = 0.2}):Play()
    end)
    
    if FirstTab then
        TabPage.Visible = true
        TweenService:Create(TabBtn, TweenInfo.new(0.2), {BackgroundTransparency = 0.2}):Play()
        FirstTab = false
    end
    
    return TabPage
end

function CreateToggle(parentTab, toggleText, callback)
    local ToggleFrame = Instance.new("Frame")
    ToggleFrame.Size = UDim2.new(1, -10, 0, 45)
    ApplyGlassStyle(ToggleFrame, 0.5, Color3.fromRGB(255, 255, 255))
    ToggleFrame.Parent = parentTab
    
    local Txt = Instance.new("TextLabel")
    Txt.Size = UDim2.new(0.6, 0, 1, 0)
    Txt.Position = UDim2.new(0, 15, 0, 0)
    Txt.BackgroundTransparency = 1
    Txt.Text = toggleText
    Txt.TextColor3 = Color3.fromRGB(255, 255, 255)
    Txt.TextSize = 14
    Txt.Font = Enum.Font.Gotham
    Txt.TextXAlignment = Enum.TextXAlignment.Left
    Txt.Parent = ToggleFrame
    
    local Switch = Instance.new("TextButton")
    Switch.Size = UDim2.new(0, 50, 0, 26)
    Switch.Position = UDim2.new(1, -65, 0.5, -13)
    Switch.Text = ""
    ApplyGlassStyle(Switch, 0.6, Color3.fromRGB(0, 120, 255))
    Switch.Parent = ToggleFrame
    
    local Slider = Instance.new("Frame")
    Slider.Size = UDim2.new(0, 20, 0, 20)
    Slider.Position = UDim2.new(0, 3, 0.5, -10)
    Slider.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
    local sliderCorner = Instance.new("UICorner")
    sliderCorner.CornerRadius = UDim.new(1, 0)
    sliderCorner.Parent = Slider
    Slider.Parent = Switch
    
    local toggled = false
    Switch.MouseButton1Click:Connect(function()
        toggled = not toggled
        if toggled then
            TweenService:Create(Slider, TweenInfo.new(0.2), {Position = UDim2.new(1, -23, 0.5, -10), BackgroundColor3 = Color3.fromRGB(255, 215, 0)}):Play()
            TweenService:Create(Switch, TweenInfo.new(0.2), {BackgroundColor3 = Color3.fromRGB(0, 120, 255)}):Play()
        else
            TweenService:Create(Slider, TweenInfo.new(0.2), {Position = UDim2.new(0, 3, 0.5, -10), BackgroundColor3 = Color3.fromRGB(255, 255, 255)}):Play()
            TweenService:Create(Switch, TweenInfo.new(0.2), {BackgroundColor3 = Color3.fromRGB(20, 30, 50)}):Play()
        end
        pcall(callback, toggled)
    end)
end

function CreateTextBoxConfig(parentTab, text, placeholder, callback)
    local BoxFrame = Instance.new("Frame")
    BoxFrame.Size = UDim2.new(1, -10, 0, 45)
    ApplyGlassStyle(BoxFrame, 0.5, Color3.fromRGB(255,255,255))
    BoxFrame.Parent = parentTab
    
    local Txt = Instance.new("TextLabel")
    Txt.Size = UDim2.new(0.6, 0, 1, 0)
    Txt.Position = UDim2.new(0, 15, 0, 0)
    Txt.BackgroundTransparency = 1
    Txt.Text = text
    Txt.TextColor3 = Color3.fromRGB(255, 255, 255)
    Txt.TextSize = 14
    Txt.Font = Enum.Font.Gotham
    Txt.TextXAlignment = Enum.TextXAlignment.Left
    Txt.Parent = BoxFrame
    
    local Input = Instance.new("TextBox")
    Input.Size = UDim2.new(0, 70, 0, 28)
    Input.Position = UDim2.new(1, -85, 0.5, -14)
    Input.PlaceholderText = placeholder
    Input.Text = ""
    Input.TextColor3 = Color3.fromRGB(255, 215, 0)
    Input.Font = Enum.Font.GothamBold
    Input.TextSize = 14
    ApplyGlassStyle(Input, 0.4, Color3.fromRGB(0, 120, 255))
    Input.Parent = BoxFrame
    
    Input.FocusLost:Connect(function(enterPressed)
        if enterPressed then
            pcall(callback, tonumber(Input.Text))
        end
    end)
end

function CreateButton(parentTab, btnText, callback)
    local Btn = Instance.new("TextButton")
    Btn.Size = UDim2.new(1, -10, 0, 40)
    Btn.Text = btnText
    Btn.TextColor3 = Color3.fromRGB(255, 255, 255)
    Btn.TextSize = 14
    Btn.Font = Enum.Font.GothamMedium
    ApplyGlassStyle(Btn, 0.4, Color3.fromRGB(0, 120, 255))
    Btn.Parent = parentTab
    
    Btn.MouseButton1Click:Connect(function()
        local oldColor = Btn.UIStroke.Color
        Btn.UIStroke.Color = Color3.fromRGB(255, 215, 0)
        task.wait(0.1)
        Btn.UIStroke.Color = oldColor
        pcall(callback)
    end)
end

function CreateLabel(parentTab, labelText)
    local LabelFrame = Instance.new("Frame")
    LabelFrame.Size = UDim2.new(1, -10, 0, 40)
    ApplyGlassStyle(LabelFrame, 0.6, Color3.fromRGB(255, 255, 255))
    LabelFrame.Parent = parentTab
    
    local Txt = Instance.new("TextLabel")
    Txt.Size = UDim2.new(1, -20, 1, 0)
    Txt.Position = UDim2.new(0, 15, 0, 0)
    Txt.BackgroundTransparency = 1
    Txt.Text = labelText
    Txt.TextColor3 = Color3.fromRGB(255, 255, 255)
    Txt.TextSize = 14
    Txt.Font = Enum.Font.GothamMedium
    Txt.TextXAlignment = Enum.TextXAlignment.Left
    Txt.Parent = LabelFrame
    
    return LabelFrame
end

function CreateCopyButton(parentTab, btnText, textToCopy)
    local CopyBtn = Instance.new("TextButton")
    CopyBtn.Size = UDim2.new(1, -10, 0, 40)
    CopyBtn.Text = btnText
    CopyBtn.TextColor3 = Color3.fromRGB(255, 255, 255)
    CopyBtn.TextSize = 14
    CopyBtn.Font = Enum.Font.GothamBold
    ApplyGlassStyle(CopyBtn, 0.4, Color3.fromRGB(0, 120, 255))
    CopyBtn.Parent = parentTab
    
    CopyBtn.MouseButton1Click:Connect(function()
        local oldColor = CopyBtn.UIStroke.Color
        CopyBtn.UIStroke.Color = Color3.fromRGB(255, 215, 0)
        
        if setclipboard then
            setclipboard(textToCopy)
        elseif toclipboard then
            toclipboard(textToCopy)
        end
        
        CopyBtn.Text = "✅ Copied Link!"
        task.wait(1.5)
        CopyBtn.Text = btnText
        CopyBtn.UIStroke.Color = oldColor
    end)
end

-- FUNCTION: DROPDOWN CHỌN NGƯỜI CHƠI & TELEPORT
function CreateDropdown(parentTab, dropdownText, callback)
    local DropdownFrame = Instance.new("Frame")
    DropdownFrame.Size = UDim2.new(1, -10, 0, 45)
    ApplyGlassStyle(DropdownFrame, 0.5, Color3.fromRGB(255, 255, 255))
    DropdownFrame.Parent = parentTab
    DropdownFrame.ClipsDescendants = true -- Để ẩn danh sách khi thu nhỏ
    
    local MainBtn = Instance.new("TextButton")
    MainBtn.Size = UDim2.new(1, 0, 0, 45)
    MainBtn.BackgroundTransparency = 1
    MainBtn.Text = dropdownText .. " 🔽"
    MainBtn.TextColor3 = Color3.fromRGB(255, 255, 255)
    MainBtn.TextSize = 14
    MainBtn.Font = Enum.Font.GothamMedium
    MainBtn.Parent = DropdownFrame
    
    local OptionsFrame = Instance.new("ScrollingFrame")
    OptionsFrame.Size = UDim2.new(1, -10, 0, 120)
    OptionsFrame.Position = UDim2.new(0, 5, 0, 50)
    OptionsFrame.BackgroundTransparency = 1
    OptionsFrame.ScrollBarThickness = 2
    OptionsFrame.CanvasSize = UDim2.new(0, 0, 0, 0)
    OptionsFrame.Parent = DropdownFrame
    
    local ListLayout = Instance.new("UIListLayout")
    ListLayout.Padding = UDim.new(0, 5)
    ListLayout.Parent = OptionsFrame
    
    ListLayout:GetPropertyChangedSignal("AbsoluteContentSize"):Connect(function()
        OptionsFrame.CanvasSize = UDim2.new(0, 0, 0, ListLayout.AbsoluteContentSize.Y + 10)
    end)

    local isOpen = false
    
    -- Hàm làm mới danh sách người chơi khi bấm mở Dropdown
    local function RefreshOptions()
        for _, child in pairs(OptionsFrame:GetChildren()) do
            if child:IsA("TextButton") then child:Destroy() end
        end
        
        for _, p in pairs(game:GetService("Players"):GetPlayers()) do
            if p ~= game:GetService("Players").LocalPlayer then -- Không hiện tên bản thân
                local OptBtn = Instance.new("TextButton")
                OptBtn.Size = UDim2.new(1, 0, 0, 30)
                OptBtn.Text = p.Name
                OptBtn.TextColor3 = Color3.fromRGB(230, 230, 230)
                OptBtn.TextSize = 13
                OptBtn.Font = Enum.Font.Gotham
                ApplyGlassStyle(OptBtn, 0.6, Color3.fromRGB(0, 120, 255))
                OptBtn.Parent = OptionsFrame
                
                OptBtn.MouseButton1Click:Connect(function()
                    MainBtn.Text = p.Name .. " 🔽"
                    isOpen = false
                    TweenService:Create(DropdownFrame, TweenInfo.new(0.2), {Size = UDim2.new(1, -10, 0, 45)}):Play()
                    pcall(callback, p.Name)
                end)
            end
        end
    end

    MainBtn.MouseButton1Click:Connect(function()
        isOpen = not isOpen
        if isOpen then
            RefreshOptions()
            TweenService:Create(DropdownFrame, TweenInfo.new(0.2), {Size = UDim2.new(1, -10, 0, 180)}):Play()
        else
            TweenService:Create(DropdownFrame, TweenInfo.new(0.2), {Size = UDim2.new(1, -10, 0, 45)}):Play()
        end
    end)
end

-------------------------------------------------------------------------------
-- 5. CONFIGURATION & GAME ID ROUTING (AUTO TAB RESET)
-------------------------------------------------------------------------------
local function ClearAllTabs()
    FirstTab = true
    for _, child in pairs(Sidebar:GetChildren()) do
        if child:IsA("TextButton") then child:Destroy() end
    end
    for _, child in pairs(Container:GetChildren()) do
        if child:IsA("ScrollingFrame") then child:Destroy() end
    end
end

if currentId == 99078474560152 then
    -------------------------------------------------------------------------------
    -- LOCATION: M.E.G GAMEPLAY MAP
    -------------------------------------------------------------------------------
    ClearAllTabs()
    
    local MainTab = CreateTab("🏠 Home")
    local PlayerTab = CreateTab("⚡ Player")
    local TrollTab = CreateTab("🖥️ Troll")
    local ElevatorTab = CreateTab("🚪 Elevator")
    local vibeTab = CreateTab("📺 Visuals")
    local InformationTab = CreateTab("ℹ️ Info")

    local customSpeed = 16
    local speedConnection = nil

    CreateTextBoxConfig(PlayerTab, "WalkSpeed Value", "16", function(value)
        if value then customSpeed = value end
    end)

    CreateToggle(PlayerTab, "Enable WalkSpeed", function(state)
        if speedConnection then speedConnection:Disconnect(); speedConnection = nil end
        if state then
            speedConnection = game:GetService("RunService").RenderStepped:Connect(function()
                local char = LocalPlayer.Character
                local humanoid = char and char:FindFirstChildOfClass("Humanoid")
                local hrp = char and char:FindFirstChild("HumanoidRootPart")
                if humanoid and hrp and humanoid.MoveDirection.Magnitude > 0 then
                    local setSpeed = (customSpeed - humanoid.WalkSpeed) / 100
                    hrp.CFrame = hrp.CFrame + (humanoid.MoveDirection * setSpeed)
                end
            end)
        else
            if speedConnection then speedConnection:Disconnect(); speedConnection = nil end
        end
    end)

    CreateToggle(PlayerTab, "Enable ESP Players", function(state)
        _G.ESP = state
        local function addESP(player)
            if player == LocalPlayer then return end
            local char = player.Character or player.CharacterAdded:Wait()
            local hrp = char:WaitForChild("HumanoidRootPart", 5)
            if hrp and _G.ESP then
                if not hrp:FindFirstChild("GlassESP") then
                    local box = Instance.new("BoxHandleAdornment")
                    box.Name = "GlassESP"
                    box.Size = Vector3.new(4, 6, 4)
                    box.AlwaysOnTop = true
                    box.ZIndex = 5
                    box.Color3 = Color3.fromRGB(0, 120, 255)
                    box.Transparency = 0.5
                    box.Adornee = hrp
                    box.Parent = hrp
                end
            end
        end

        if state then
            for _, p in pairs(Players:GetPlayers()) do
                task.spawn(function() addESP(p) end)
                p.CharacterAdded:Connect(function()
                    if _G.ESP then task.wait(0.5); addESP(p) end
                end)
            end
            _G.PlayerAddedConnection = Players.PlayerAdded:Connect(function(newPlayer)
                newPlayer.CharacterAdded:Connect(function()
                    if _G.ESP then task.wait(0.5); addESP(newPlayer) end
                end)
            end)
        else
            if _G.PlayerAddedConnection then _G.PlayerAddedConnection:Disconnect(); _G.PlayerAddedConnection = nil end
            for _, p in pairs(Players:GetPlayers()) do
                if p.Character and p.Character:FindFirstChild("HumanoidRootPart") then
                    local esp = p.Character.HumanoidRootPart:FindFirstChild("GlassESP")
                    if esp then esp:Destroy() end
                end
            end
        end
    end)

    local currentFlySpeed = 50
    local flyActive = false
    local flyConnection = nil

    CreateTextBoxConfig(PlayerTab, "Fly Speed Value", "50", function(value)
        if value and value > 0 then currentFlySpeed = value end
    end)

    CreateToggle(PlayerTab, "Enable Fly", function(state)
        flyActive = state
        if flyConnection then flyConnection:Disconnect(); flyConnection = nil end
        local char = LocalPlayer.Character
        if not char then return end
        local hrp = char:FindFirstChild("HumanoidRootPart")
        local humanoid = char:FindFirstChildOfClass("Humanoid")
        if not hrp or not humanoid then return end

        if state then
            local bv = Instance.new("BodyVelocity")
            bv.Name = "FlyVelocity"
            bv.MaxForce = Vector3.new(9e9, 9e9, 9e9)
            bv.Velocity = Vector3.zero
            bv.Parent = hrp

            flyConnection = game:GetService("RunService").RenderStepped:Connect(function()
                if not flyActive or not char.Parent then return end
                local moveDir = humanoid.MoveDirection
                if moveDir.Magnitude > 0 then
                    bv.Velocity = moveDir.Unit * currentFlySpeed
                else
                    bv.Velocity = Vector3.new(0, 0.1, 0)
                end
            end)
        else
            local old = hrp:FindFirstChild("FlyVelocity")
            if old then old:Destroy() end
        end
    end)

    local Lighting = game:GetService("Lighting")
    local oldAmbient = Lighting.Ambient
    local oldColorShift = Lighting.ColorShift_Top
    local oldBrightness = Lighting.Brightness
    local oldFogEnd = Lighting.FogEnd

    CreateToggle(PlayerTab, "Enable Full Bright", function(state)
        if state then
            Lighting.Ambient = Color3.fromRGB(255, 255, 255)
            Lighting.ColorShift_Top = Color3.fromRGB(255, 255, 255)
            Lighting.Brightness = 2
            Lighting.FogEnd = 9e9
        else
            Lighting.Ambient = oldAmbient; Lighting.ColorShift_Top = oldColorShift; Lighting.Brightness = oldBrightness; Lighting.FogEnd = oldFogEnd
        end
    end)

    local godModeActive = false
    CreateToggle(PlayerTab, "Enable God Mode", function(state)
        godModeActive = state
        if state then
            task.spawn(function()
                while godModeActive do
                    task.wait(0.1)
                    local char = LocalPlayer.Character
                    local humanoid = char and char:FindFirstChildOfClass("Humanoid")
                    if humanoid and humanoid.Health > 0 then
                        local currentCFrame = char.HumanoidRootPart.CFrame
                        local clone = humanoid:Clone()
                        clone.Parent = char
                        humanoid:Destroy()
                        LocalPlayer.Character = char
                        char.HumanoidRootPart.CFrame = currentCFrame
                        workspace.CurrentCamera.CameraSubject = char:FindFirstChildOfClass("Humanoid")
                    end
                end
            end)
        else
            local char = LocalPlayer.Character
            local humanoid = char and char:FindFirstChildOfClass("Humanoid")
            if humanoid then humanoid.Health = 0 end
        end
    end)

    CreateButton(vibeTab, "📺 Vintage 2018 Graphics", function()
        pcall(function() Lighting.Technology = Enum.Technology.Voxel end)
        Lighting.Brightness = 3; Lighting.GlobalShadows = true
        Lighting.Ambient = Color3.fromRGB(140, 140, 140); Lighting.OutdoorAmbient = Color3.fromRGB(128, 128, 128)
        for _, effect in pairs(Lighting:GetChildren()) do
            if effect:IsA("BloomEffect") or effect:IsA("BlurEffect") or effect:IsA("DepthOfFieldEffect") or effect:IsA("SunRaysEffect") then
                effect.Enabled = false
            end
        end
        local atm = Lighting:FindFirstChildOfClass("Atmosphere")
        if atm then atm.Parent = game:GetService("TestService") end
        Lighting.FogEnd = 100000; Lighting.FogStart = 0
    end)

    CreateButton(vibeTab, "🤖 Morph into Classic Noob", function()
        local char = LocalPlayer.Character
        if not char then return end
        for _, obj in pairs(char:GetChildren()) do
            if obj:IsA("Accessory") or obj:IsA("Shirt") or obj:IsA("Pants") or obj:IsA("ShirtGraphic") or obj:IsA("CharacterMesh") then obj:Destroy() end
        end
        if char:FindFirstChild("Torso") and char.Torso:FindFirstChildOfClass("Decal") then char.Torso:FindFirstChildOfClass("Decal"):Destroy() end
        local function colorPart(partName, color)
            local part = char:FindFirstChild(partName)
            if part and part:IsA("BasePart") then part.BrickColor = BrickColor.new(color); part.Color = BrickColor.new(color).Color end
        end
        colorPart("Head", "Bright yellow"); colorPart("Left Arm", "Bright yellow"); colorPart("Right Arm", "Bright yellow")
        colorPart("Torso", "Bright blue")
        colorPart("Left Leg", "Bright green"); colorPart("Right Leg", "Bright green")
    end)

    CreateButton(TrollTab, "🖥️ Turn Off Active Computer", function()
        ReplicatedStorage:WaitForChild("computerOff"):FireServer()
    end)

    CreateButton(TrollTab, "🖥️ Turn On Computer Again", function()
        ReplicatedStorage:WaitForChild("computerOn"):FireServer()
    end)

    CreateButton(TrollTab, "🚪 Force Open Elevator Door", function()
        ReplicatedStorage:WaitForChild("OpenElevator"):FireServer()
    end)

    CreateButton(ElevatorTab, "⚡ Teleport to Elevator", function()
        local elevator = workspace:FindFirstChild("Elevator")
        local hrp = LocalPlayer.Character and LocalPlayer.Character:FindFirstChild("HumanoidRootPart")
        if elevator and hrp then
            local targetPart = elevator:IsA("Model") and (elevator.PrimaryPart or elevator:FindFirstChildWhichIsA("BasePart")) or elevator
            if targetPart then hrp.CFrame = targetPart.CFrame * CFrame.new(0, 3, 0) end
        end
    end)

    CreateButton(ElevatorTab, "🧭 Locate Elevator (Show Compass)", function()
        local eventsFolder = ReplicatedStorage:FindFirstChild("Events")
        local compass = eventsFolder and eventsFolder:FindFirstChild("CompassEvent")
        if compass then
            compass:FireServer(LocalPlayer, "Elevator")
        end
    end)

    CreateToggle(ElevatorTab, "Enable Elevator ESP", function(state)
        local elevator = workspace:FindFirstChild("Elevator") or workspace:FindFirstChild("ThangMáy")
        if state then
            if elevator and not elevator:FindFirstChild("TrollHub_ESP") then
                local highlight = Instance.new("Highlight")
                highlight.Name = "TrollHub_ESP"
                highlight.FillColor = Color3.fromRGB(255, 0, 0)
                highlight.FillTransparency = 0.5
                highlight.OutlineColor = Color3.fromRGB(255, 215, 0)
                highlight.Parent = elevator
            end
        else
            if elevator then
                local esp = elevator:FindFirstChild("TrollHub_ESP")
                if esp then esp:Destroy() end
            end
        end
    end)

    CreateLabel(MainTab, "Features are fully operational! ESP, Troll, Speed, and Fly are active. Report bugs if any.")
    CreateLabel(MainTab, "Note: Set speed config to 90 before exceeding the 90 limit.")
    
    CreateLabel(InformationTab, "👑 Owner: Haianh-trollhub")
    CreateLabel(InformationTab, "🚀 Version: Troll Hub M.E.G v2.0")
    CreateLabel(InformationTab, "📅 Last Update: 15/06/2026")
    CreateLabel(InformationTab, "💬 Join our community via the link below!")

elseif currentId == 98629859043211 then
    -------------------------------------------------------------------------------
    -- LOCATION: M.E.G LOBBY MAP
    -------------------------------------------------------------------------------
    ClearAllTabs()
    
    local MainTab = CreateTab("🏠 Lobby")
    local InformationTab = CreateTab("ℹ️ Info")

    CreateLabel(MainTab, "📌 You are currently in the Lobby. Main gameplay features are hidden!")

    CreateLabel(InformationTab, "👑 Owner: Haianh-trollhub")
    CreateLabel(InformationTab, "🚀 Version: Troll Hub M.E.G v2.0")
    CreateLabel(InformationTab, "📅 Last Update: 15/06/2026")

elseif currentId == 6516141723 or currentId == 6839171747 then
    -------------------------------------------------------------------------------
    -- LOCATION: DOORS GAME
    -------------------------------------------------------------------------------
    ClearAllTabs()
    
    local MainTab = CreateTab("🚪 DOORS Main")
    local InformationTab = CreateTab("ℹ️ Info")

-- ==================== 1. TOGGLE FULL BRIGHT ====================
local brightConnection
local originalAmbient = game:GetService("Lighting").Ambient

CreateToggle(MainTab, "Full Bright", function(state)
    if state then
        -- Bật làm sáng map
        game:GetService("Lighting").Ambient = Color3.fromRGB(255, 255, 255)
        game:GetService("Lighting").Brightness = 2
        
        -- Giữ sáng liên tục phòng trường hợp game tự chỉnh tối lại
        brightConnection = game:GetService("Lighting").Changed:Connect(function()
            if state then
                game:GetService("Lighting").Ambient = Color3.fromRGB(255, 255, 255)
                game:GetService("Lighting").Brightness = 2
            end
        end)
    else
        -- Tắt, trả về độ tối mặc định của game
        if brightConnection then brightConnection:Disconnect() end
        game:GetService("Lighting").Ambient = originalAmbient
        game:GetService("Lighting").Brightness = 1
    end
end)


-- ==================== HÀM HỖ TRỢ ESP (DÙNG CHUNG) ====================
local function createESP(object, color, name)
    if object:FindFirstChild("DoorsESP") then return end
    
    local highlight = Instance.new("Highlight")
    highlight.Name = "DoorsESP"
    highlight.FillColor = color
    highlight.FillOpacity = 0.4
    highlight.OutlineColor = Color3.fromRGB(255, 255, 255)
    highlight.OutlineOpacity = 1
    highlight.Adornee = object
    highlight.Parent = object
    
    local billboard = Instance.new("BillboardGui")
    billboard.Name = "DoorsText"
    billboard.Size = UDim2.new(0, 100, 0, 30)
    billboard.AlwaysOnTop = true
    billboard.StudsOffset = Vector3.new(0, 3, 0)
    billboard.Adornee = object
    
    local textLabel = Instance.new("TextLabel")
    textLabel.Size = UDim2.new(1, 0, 1, 0)
    textLabel.BackgroundTransparency = 1
    textLabel.Text = name
    textLabel.TextColor3 = color
    textLabel.TextSize = 14
    textLabel.Font = Enum.Font.SourceSansBold
    textLabel.Parent = billboard
    
    billboard.Parent = object
end

local function removeESP(object)
    if object:FindFirstChild("DoorsESP") then object.DoorsESP:Destroy() end
    if object:FindFirstChild("DoorsText") then object.DoorsText:Destroy() end
end


-- ==================== 2. TOGGLE ESP CỬA ====================
local doorESPActive = false
task.spawn(function()
    while task.wait(1) do
        if doorESPActive then
            for _, obj in ipairs(workspace:GetDescendants()) do
                if obj.Name == "Door" and obj:FindFirstChild("ClientDoor") then
                    createESP(obj, Color3.fromRGB(0, 255, 0), "Cửa Đi Tiếp")
                end
            end
        end
    end
end)

CreateToggle(MainTab, "ESP Cửa", function(state)
    doorESPActive = state
    if not state then
        for _, obj in ipairs(workspace:GetDescendants()) do
            if obj.Name == "Door" then removeESP(obj) end
        end
    end
end)


-- ==================== 3. TOGGLE ESP TỦ ====================
local closetESPActive = false
task.spawn(function()
    while task.wait(1) do
        if closetESPActive then
            for _, obj in ipairs(workspace:GetDescendants()) do
                if obj.Name == "Wardrobe" or obj.Name == "Closet" then
                    createESP(obj, Color3.fromRGB(0, 162, 255), "Tủ Trốn")
                end
            end
        end
    end
end)

CreateToggle(MainTab, "ESP Tủ Trốn", function(state)
    closetESPActive = state
    if not state then
        for _, obj in ipairs(workspace:GetDescendants()) do
            if obj.Name == "Wardrobe" or obj.Name == "Closet" then removeESP(obj) end
        end
    end
end)


-- ==================== 4. TOGGLE ESP SÁCH ====================
local bookESPActive = false
task.spawn(function()
    while task.wait(1) do
        if bookESPActive then
            for _, obj in ipairs(workspace:GetDescendants()) do
                if obj.Name == "LiveHintBook" or (obj:IsA("Model") and obj.Name == "Book") then
                    createESP(obj, Color3.fromRGB(255, 234, 0), "Sách Mật Mã")
                end
            end
        end
    end
end)

CreateToggle(MainTab, "ESP Sách Phòng 50", function(state)
    bookESPActive = state
    if not state then
        for _, obj in ipairs(workspace:GetDescendants()) do
            if obj.Name == "LiveHintBook" or obj.Name == "Book" then removeESP(obj) end
        end
    end
end)

    CreateLabel(MainTab, "🚪 Successfully loaded into DOORS! Features are currently being updated...")

    CreateLabel(InformationTab, "👑 Owner: Haianh-trollhub")
    CreateLabel(InformationTab, "🚀 Version: Troll Hub DOORS v1.0")
    CreateLabel(InformationTab, "📅 Last Update: 19/06/2026")

elseif currentId == 88323040672117 then
    -------------------------------------------------------------------------------
    -- LOCATION: DIVAZ GAME (TRANSLATED TO ENGLISH & FIXED)
    -------------------------------------------------------------------------------
    ClearAllTabs()
    
    local mainTab = CreateTab("⚡ Player")
    local infoTab = CreateTab("ℹ️ Info")
    
    local customSpeed = 16
    local speedConnection = nil

    -- Sửa từ PlayerTab thành mainTab và đổi sang tiếng Anh
    CreateTextBoxConfig(mainTab, "WalkSpeed Value", "16", function(value)
        if value then customSpeed = value end
    end)

    CreateToggle(mainTab, "Enable WalkSpeed", function(state)
        if speedConnection then speedConnection:Disconnect(); speedConnection = nil end
        if state then
            speedConnection = game:GetService("RunService").RenderStepped:Connect(function()
                local char = LocalPlayer.Character
                local humanoid = char and char:FindFirstChildOfClass("Humanoid")
                local hrp = char and char:FindFirstChild("HumanoidRootPart")
                if humanoid and hrp and humanoid.MoveDirection.Magnitude > 0 then
                    local setSpeed = (customSpeed - humanoid.WalkSpeed) / 100
                    hrp.CFrame = hrp.CFrame + (humanoid.MoveDirection * setSpeed)
                end
            end)
        else
            if speedConnection then speedConnection:Disconnect(); speedConnection = nil end
        end
    end)

    CreateToggle(mainTab, "Enable ESP Players", function(state)
        _G.ESP = state
        local function addESP(player)
            if player == LocalPlayer then return end
            local char = player.Character or player.CharacterAdded:Wait()
            local hrp = char:WaitForChild("HumanoidRootPart", 5)
            if hrp and _G.ESP then
                if not hrp:FindFirstChild("GlassESP") then
                    local box = Instance.new("BoxHandleAdornment")
                    box.Name = "GlassESP"
                    box.Size = Vector3.new(4, 6, 4)
                    box.AlwaysOnTop = true
                    box.ZIndex = 5
                    box.Color3 = Color3.fromRGB(0, 120, 255)
                    box.Transparency = 0.5
                    box.Adornee = hrp
                    box.Parent = hrp
                end
            end
        end

        if state then
            for _, p in pairs(Players:GetPlayers()) do
                task.spawn(function() addESP(p) end)
                p.CharacterAdded:Connect(function()
                    if _G.ESP then task.wait(0.5); addESP(p) end
                end)
            end
            _G.PlayerAddedConnection = Players.PlayerAdded:Connect(function(newPlayer)
                newPlayer.CharacterAdded:Connect(function()
                    if _G.ESP then task.wait(0.5); addESP(newPlayer) end
                end)
            end)
        else
            if _G.PlayerAddedConnection then _G.PlayerAddedConnection:Disconnect(); _G.PlayerAddedConnection = nil end
            for _, p in pairs(Players:GetPlayers()) do
                if p.Character and p.Character:FindFirstChild("HumanoidRootPart") then
                    local esp = p.Character.HumanoidRootPart:FindFirstChild("GlassESP")
                    if esp then esp:Destroy() end
                end
            end
        end
    end)

        -- Bổ sung thêm biến để lưu trạng thái auto teleport
    local autoTeleport = false
    local targetPlayerName = nil

    -- Dropdown chọn người chơi
    CreateDropdown(mainTab, "Select Player", function(targetName)
        targetPlayerName = targetName -- Lưu tên người chơi được chọn
    end)

    CreateButton(mainTab, "🔄 Refresh Player List", function()
    -- Gọi lại hàm làm mới danh sách (chỉ hoạt động nếu dropdown đang mở hoặc được kích hoạt lại)
    -- Để tối ưu, nút này sẽ ép giao diện dropdown cập nhật lại danh sách người chơi mới nhất hiện tại
    local dropdown = mainTab:FindFirstChildWhichIsA("Frame") -- Tìm khung dropdown trong tab
    if dropdown then
        local mainBtn = dropdown:FindFirstChildOfClass("TextButton")
        if mainBtn then
            -- Giả lập hành động click để dropdown tự động xóa danh sách cũ và quét lại người chơi đang online
            mainBtn.Text = "Select Player 🔽"
        end
    end
end)

    -- Toggle để bật/tắt Auto Teleport
    CreateToggle(mainTab, "Enable Auto Teleport", function(state)
        autoTeleport = state
        if autoTeleport then
            task.spawn(function()
                while autoTeleport do
                    task.wait(0.1) -- Cập nhật vị trí mỗi 0.1 giây
                    if targetPlayerName then
                        local targetPlayer = game:GetService("Players"):FindFirstChild(targetPlayerName)
                        local targetChar = targetPlayer and targetPlayer.Character
                        local localChar = game:GetService("Players").LocalPlayer.Character
                        
                        if targetChar and localChar then
                            local targetHRP = targetChar:FindFirstChild("HumanoidRootPart")
                            local localHRP = localChar:FindFirstChild("HumanoidRootPart")
                            
                            if targetHRP and localHRP then
                                localHRP.CFrame = targetHRP.CFrame * CFrame.new(0, 3, 0)
                            end
                        end
                    end
                end
            end)
        end
    end)

    -- Thêm thông tin Info bằng tiếng Anh cho đồng bộ
    CreateLabel(infoTab, "👑 Owner: Haianh-trollhub")
    CreateLabel(infoTab, "🚀 Version: Troll Hub Divaz v1.0")
    CreateLabel(infoTab, "📅 Last Update: 20/06/2026")
    CreateCopyButton(infoTab, "🔗 Copy Discord Invite", "https://discord.gg/QfjXycjQA")

elseif currentId == 97598239454123 then
    -------------------------------------------------------------------------------
    -- LOCATION: GROW A GARDEN 2
    -------------------------------------------------------------------------------
    ClearAllTabs()

    local MainTab = CreateTab("MainTab")
    local infoTab = CreateTab("information")
    
    -- ==================== TOGGLE AUTO PICKUP GOLD SEED (CHUẨN CẤU TRÚC) ====================
local autoSeedActive = false
local farmLoop -- Biến dùng để quản lý vòng lặp tránh bị nhân bản (lag game)

CreateToggle(MainTab, "Auto Pick Gold Seed", function(state)
    autoSeedActive = state
    
    -- Nếu bật Toggle và vòng lặp chưa chạy thì mới kích hoạt tính năng ở dưới
    if state and not farmLoop then
        farmLoop = task.spawn(function()
            while autoSeedActive do -- Vòng lặp sẽ chạy liên tục KHI VÀ CHỈ KHI toggle bật
                local pLayer = game:GetService("Players").LocalPlayer
                local char = pLayer.Character
                
                if char and char:FindFirstChild("HumanoidRootPart") then
                    for _, obj in ipairs(workspace:GetDescendants()) do
                        -- Quét tìm hạt giống vàng
                        if obj:IsA("Model") and (string.find(string.lower(obj.Name), "seed") and string.find(string.lower(obj.Name), "gold")) or obj.Name == "Gold Seed" then
                            local targetPart = obj:FindFirstChildHorizontalAlignment or obj:FindFirstChildWhichIsA("BasePart")
                            
                            if targetPart then
                                local oldCFrame = char.HumanoidRootPart.CFrame
                                
                                -- Teleport đến nhặt cực nhanh
                                char.HumanoidRootPart.CFrame = targetPart.CFrame
                                task.wait(0.05)
                                
                                -- Trả về vị trí cũ
                                char.HumanoidRootPart.CFrame = oldCFrame
                                break 
                            end
                        end
                    end
                end
                task.wait(0.1) -- Khoảng nghỉ giữa các lần quét hạt giống
            end
            
            -- Nếu tắt toggle, xóa trạng thái vòng lặp để lần sau bật lại được
            farmLoop = nil 
        end)
    end
end)

CreateLabel(infoTab, "👑 Owner: Haianh-trollhub")
    CreateLabel(infoTab, "🚀 Version: Troll Hub Grow a Garden 2 🏡 v1.0")
    CreateLabel(infoTab, "📅 Last Update: 20/06/2026")
    CreateCopyButton(infoTab, "🔗 Copy Discord Invite", "https://discord.gg/QfjXycjQA")

elseif currentId == 7577961216 then
    -------------------------------------------------------------------------------
    -- LOCATION: SQUID GAME X (LOBBY)
    -------------------------------------------------------------------------------
    ClearAllTabs()
    
    local MainTab = CreateTab("🏠 Lobby")
    local InformationTab = CreateTab("ℹ️ Info")

    CreateLabel(MainTab, "📌 You are currently in the Lobby. Main gameplay features are hidden!")

    CreateLabel(InformationTab, "👑 Owner: Haianh-Trollhub")
    CreateLabel(InformationTab, "🚀 Version: TROLL HUB SQUID GAME X (LOBBY) version1.0")
    CreateLabel(InformationTab, "📅 Last Update: 21/06/2026")
    CreateCopyButton(InformationTab, "🔗 Copy Discord Invite", "https://discord.gg/QfjXycjQA")

elseif currentId == 7577981568 then
    -------------------------------------------------------------------------------
    -- LOCATION: SQUID GAME X 
    -------------------------------------------------------------------------------
    ClearAllTabs()
    
    local Tab1 = CreateTab("Main")
    local Tab2 =CreateTab("information")
    
    local customSpeed = 16
    local speedConnection = nil

    -- Sửa từ PlayerTab thành mainTab và đổi sang tiếng Anh
    CreateTextBoxConfig(Tab1, "WalkSpeed Value", "16", function(value)
        if value then customSpeed = value end
    end)

    CreateToggle(Tab1, "Enable WalkSpeed", function(state)
        if speedConnection then speedConnection:Disconnect(); speedConnection = nil end
        if state then
            speedConnection = game:GetService("RunService").RenderStepped:Connect(function()
                local char = LocalPlayer.Character
                local humanoid = char and char:FindFirstChildOfClass("Humanoid")
                local hrp = char and char:FindFirstChild("HumanoidRootPart")
                if humanoid and hrp and humanoid.MoveDirection.Magnitude > 0 then
                    local setSpeed = (customSpeed - humanoid.WalkSpeed) / 100
                    hrp.CFrame = hrp.CFrame + (humanoid.MoveDirection * setSpeed)
                end
            end)
        else
            if speedConnection then speedConnection:Disconnect(); speedConnection = nil end
        end
    end)

    CreateToggle(Tab1, "Enable ESP Players", function(state)
        _G.ESP = state
        local function addESP(player)
            if player == LocalPlayer then return end
            local char = player.Character or player.CharacterAdded:Wait()
            local hrp = char:WaitForChild("HumanoidRootPart", 5)
            if hrp and _G.ESP then
                if not hrp:FindFirstChild("GlassESP") then
                    local box = Instance.new("BoxHandleAdornment")
                    box.Name = "GlassESP"
                    box.Size = Vector3.new(4, 6, 4)
                    box.AlwaysOnTop = true
                    box.ZIndex = 5
                    box.Color3 = Color3.fromRGB(0, 120, 255)
                    box.Transparency = 0.5
                    box.Adornee = hrp
                    box.Parent = hrp
                end
            end
        end

        if state then
            for _, p in pairs(Players:GetPlayers()) do
                task.spawn(function() addESP(p) end)
                p.CharacterAdded:Connect(function()
                    if _G.ESP then task.wait(0.5); addESP(p) end
                end)
            end
            _G.PlayerAddedConnection = Players.PlayerAdded:Connect(function(newPlayer)
                newPlayer.CharacterAdded:Connect(function()
                    if _G.ESP then task.wait(0.5); addESP(newPlayer) end
                end)
            end)
        else
            if _G.PlayerAddedConnection then _G.PlayerAddedConnection:Disconnect(); _G.PlayerAddedConnection = nil end
            for _, p in pairs(Players:GetPlayers()) do
                if p.Character and p.Character:FindFirstChild("HumanoidRootPart") then
                    local esp = p.Character.HumanoidRootPart:FindFirstChild("GlassESP")
                    if esp then esp:Destroy() end
                end
            end
        end
    end)

CreateLabel(Tab2, "👑 Owner: Haianh-trollhub")
    CreateLabel(Tab2, "🚀 Version: TROLL HUB SQUID GAME X version 1.0")
    CreateLabel(Tab2, "📅 Last Update: 21/06/2026")
    CreateCopyButton(Tab2, "🔗 Copy Discord Invite", "https://discord.gg/QfjXycjQA")

end
-------------------------------------------------------------------------------
-- GLOBAL FOOTER BUTTON (Appears inside Info tab across all maps)
-------------------------------------------------------------------------------
if InformationTab then
    CreateCopyButton(InformationTab, "🔗 Copy Discord Invite", "https://discord.gg/QfjXycjQA")
end